# POST http://laprg03.eastus.cloudapp.azure.com:81/PViewISAPI.dll/la/rest/TView/WDame_calendario

POST http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_calendario

{
  "Json":"true"
}
###

POST http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_DatosM

{
    "Json":"true",
    "Param": {
        "Status": 0,
        "Mensaje": " ",
        "Rif": "D0040222765857"
    }
}
###

POST  http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_corden

{
	"Json":"true",
	"param": {
		"Status": 0,
		"Mensaje": "<NUORIGEN>1</NUORIGEN>",
		"Rif": "D0040222765857",
    "desde": "15-03-2018",
    "Hasta": "15-03-2018"
	}
}
###

POST http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_PosicionM_Ant

{
  "Json": "true",
  "param": {
    "Rif":"D0040222765857",
    "Fechin":"15-03-2018"
  }
}
###
