# POST http://laprg03.eastus.cloudapp.azure.com:81/PViewISAPI.dll/la/rest/TView/WDame_calendario

POST http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_calendario

{
  "Json":"true"
}
###

POST http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_DatosM

{
    "Json":"true",
    "Param": {
        "Status": 0,
        "Mensaje": " ",
        "Rif": "D0040222765857"
    }
}
###

POST  http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_corden

{
	"Json":"true",
	"param": {
		"Status": 0,
		"Mensaje": "<NUORIGEN>1</NUORIGEN>",
		"Rif": "D0040222765857",
    "desde": "15-03-2018",
    "Hasta": "15-03-2018"
	}
}
###

POST  http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_cordenX

{
	"Json":"true",
	"param": {
    "Desde": "15-03-2018",
    "Hasta": "15-03-2018",
		"Rif": "D0040222765857",
    "Nuorigen": 1,
    "Titulo": ""
	}
}
###

# CC0122
# DO8013700828
POST  http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_Titulos

{
	"Json":"true",
	"param": {
    "Cotitulo": "DO1002220627",
    "Mrkt": "",
    "Vigencia": 0,
    "Moneda": 99
	}
}
###

# Titulos masivos
# todos los titulos vigentes
POST  http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_Titulos

{
	"Json":"true",
	"param": {
    "Cotitulo": "",
    "Mrkt": "P",
    "Vigencia": 1,
    "Moneda": -1
	}
}
###

POST http://la2k12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_PosicionM_Ant

{
  "Json": "true",
  "param": {
    "Rif":"D0040222765857",
    "Fechin":"15-03-2018"
  }
}
###

POST http://la2K12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_permiso_usuario

{
  "Json":"true",
  "param": {
    "User": "ALO",
    "Codigo": "J"
  }
}
###


POST http://la2K12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WAutentica_usuario

{
  "Json":"True",
  "param": {
    "User": "LASISTEMAS",
    "Pass": "ALO103"
  }
}
###


POST http://la2K12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WDame_IDMRif

{
  "Json":"True",
  "param": {
    "Id": "ACO001",
    "Cual": "I"
  }
}
###

# ESTOS LLAMAR DIRECTO EN EL PROYECTO SIN LIBRERIA
# INCORPORAR "User": "USUARIO" + Usuariobv

# Posturas Propias BVRD
POST http://la2K12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WdamePosturasPropias

{
  "Json":"false",
  "param": {
    "User": "USUARIO1"
  }
}
###

# Operaciones Propias BVRD
POST http://la2K12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WdameOperacionesPropias

{
  "Json":"False",
  "param": {
    "User": "USUARIO1"
  }
}
###

# Posturas Mercado BVRD
POST http://la2K12.eastus.cloudapp.azure.com:8079/pview/PViewISAPI.dll/la/rest/TView/WdamePosturasSiopel

{
    "Json":"False",
    "param": {
        "User": "USUARIO1"
    }
}
###


GET http://52.206.163.34/apibvrdposturaspropias/laexcel/Zzr3ll4RNW

###

GET http://52.206.163.34/apibvrdoperacionespropias/laexcel/Zzr3ll4RNW

###


GET http://52.206.163.34/apibvrdposturassiopel/laexcel/Zzr3ll4RNW

###
